name: Node.js Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 #ambil code
      - uses: actions/setup-node@v4 #setup nodejs, pakai versi 18
        with:
          node-version: 18
          
      - run: npm install #install npm
      
      - run: npm test #test npm

      - run: npm start & #start npm di background karena ada &

      - run: sleep 5 #delay 5 detik, kaya tunggu dulu 5 detik

      - run: curl http://localhost:3000 #ini endepointnya akan muncul pas proses workflow di actions
